# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.2
    hooks:
      - id: style-files
        args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
        additional_dependencies:
          - mlr-org/styler.mlr
      - id: roxygenize
        additional_dependencies:
          - Ecdat
          - GGally
          - R6
          - Rcpp
          - bujar
          - checkmate
          - coxed
          - data.table
          - ggplot2
          - mlr3
          - mlr3misc
          - mlr3pipelines
          - mlr3viz
          - paradox
          - simsurv
          - survAUC
          - survival
          - survivalmodels
          - xoopR/distr6
      # codemeta must be above use-tidy-description when both are used
      - id: use-tidy-description
      - id: readme-rmd-rendered
      - id: parsable-R
      - id: no-browser-statement
      - id: deps-in-desc
        exclude: data-raw|inst
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=200]
      - id: file-contents-sorter
        files: '^\.Rbuildignore$'
      - id: end-of-file-fixer
        exclude: '\.Rd'
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        exclude: 'inst/extdata/unemployment.rds'
ci:
  autoupdate_schedule: monthly
